-- Spatial Analysis Results Storage
-- Stores results from spatial analysis operations

-- Table for storing spatial analysis results
CREATE TABLE IF NOT EXISTS spatial_analysis_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  analysis_type TEXT NOT NULL CHECK (analysis_type IN ('buffer', 'density', 'proximity', 'statistics', 'route')),
  name TEXT NOT NULL,
  description TEXT,
  parameters JSONB NOT NULL DEFAULT '{}',
  results JSONB NOT NULL DEFAULT '{}',
  geometry GEOMETRY(Geometry, 4326),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_spatial_analysis_user ON spatial_analysis_results(user_id);
CREATE INDEX IF NOT EXISTS idx_spatial_analysis_type ON spatial_analysis_results(analysis_type);
CREATE INDEX IF NOT EXISTS idx_spatial_analysis_created ON spatial_analysis_results(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_spatial_analysis_geometry ON spatial_analysis_results USING GIST(geometry);

-- RLS Policies
ALTER TABLE spatial_analysis_results ENABLE ROW LEVEL SECURITY;

-- Users can view their own analysis results
CREATE POLICY "Users can view own analysis results"
  ON spatial_analysis_results
  FOR SELECT
  USING (auth.uid() = user_id);

-- Users can insert their own analysis results
CREATE POLICY "Users can insert own analysis results"
  ON spatial_analysis_results
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can update their own analysis results
CREATE POLICY "Users can update own analysis results"
  ON spatial_analysis_results
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Users can delete their own analysis results
CREATE POLICY "Users can delete own analysis results"
  ON spatial_analysis_results
  FOR DELETE
  USING (auth.uid() = user_id);

-- Admins can view all analysis results
CREATE POLICY "Admins can view all analysis results"
  ON spatial_analysis_results
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_roles.user_id = auth.uid()
      AND user_roles.role = 'admin'
    )
  );

-- Table for storing optimized routes
CREATE TABLE IF NOT EXISTS optimized_routes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  report_ids TEXT[] NOT NULL,
  route_points JSONB NOT NULL,
  total_distance NUMERIC NOT NULL,
  estimated_time_minutes INTEGER,
  geometry GEOMETRY(LineString, 4326),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_optimized_routes_user ON optimized_routes(user_id);
CREATE INDEX IF NOT EXISTS idx_optimized_routes_created ON optimized_routes(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_optimized_routes_geometry ON optimized_routes USING GIST(geometry);

-- RLS Policies for optimized_routes
ALTER TABLE optimized_routes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own routes"
  ON optimized_routes
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own routes"
  ON optimized_routes
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own routes"
  ON optimized_routes
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own routes"
  ON optimized_routes
  FOR DELETE
  USING (auth.uid() = user_id);

CREATE POLICY "Admins can view all routes"
  ON optimized_routes
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_roles.user_id = auth.uid()
      AND user_roles.role = 'admin'
    )
  );

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for updated_at
CREATE TRIGGER update_spatial_analysis_updated_at
  BEFORE UPDATE ON spatial_analysis_results
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_optimized_routes_updated_at
  BEFORE UPDATE ON optimized_routes
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Comments
COMMENT ON TABLE spatial_analysis_results IS 'Stores results from spatial analysis operations (buffer, density, statistics, etc.)';
COMMENT ON TABLE optimized_routes IS 'Stores optimized inspection routes generated by TSP algorithm';
COMMENT ON COLUMN spatial_analysis_results.analysis_type IS 'Type of analysis: buffer, density, proximity, statistics, route';
COMMENT ON COLUMN spatial_analysis_results.parameters IS 'Input parameters used for the analysis';
COMMENT ON COLUMN spatial_analysis_results.results IS 'Analysis results in JSON format';
COMMENT ON COLUMN optimized_routes.route_points IS 'Ordered array of route points with coordinates';
COMMENT ON COLUMN optimized_routes.total_distance IS 'Total route distance in kilometers';
