// This file is automatically generated. Do not edit it directly.
/* eslint-disable @typescript-eslint/no-explicit-any */
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL_RAW = (import.meta.env.VITE_SUPABASE_URL as string | undefined)?.trim();
const SUPABASE_KEY_RAW = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined)?.trim();

function isPlaceholder(val?: string) {
  if (!val) return true;
  const lower = val.toLowerCase();
  return (
    lower.includes('your-project-ref') ||
    lower.includes('your_anon_public_key') ||
    lower === 'your_anonymous_key' ||
    lower === 'your_anon_key' ||
    lower === 'your_key' ||
    lower === 'https://.supabase.co'
  );
}

const SUPABASE_URL = !isPlaceholder(SUPABASE_URL_RAW) ? SUPABASE_URL_RAW : undefined;
const SUPABASE_PUBLISHABLE_KEY = !isPlaceholder(SUPABASE_KEY_RAW) ? SUPABASE_KEY_RAW : undefined;
export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function createSupabaseStub() {
  // Minimal no-op stub to prevent runtime crashes when env vars are missing during local dev.
  const resultOk = { data: [] as any[], error: null };
  const singleResult = { data: null, error: null };

  const makeSelectable = () => {
    const thenable: any = {
      // query builders
      eq: () => thenable,
      order: () => Promise.resolve(resultOk),
      maybeSingle: () => Promise.resolve(singleResult),
      // allow awaiting directly on select()
      then: (resolve: any) => resolve(resultOk),
      catch: () => thenable,
      finally: () => {},
    };
    return thenable;
  };

  const stub: any = {
    auth: {
      onAuthStateChange: (_cb: any) => ({ data: { subscription: { unsubscribe: () => {} } } }),
      getSession: async () => ({ data: { session: null }, error: null }),
      signOut: async () => {},
      signInWithPassword: async (_creds: any) => ({
        data: { session: null, user: null },
        error: { message: 'Supabase belum dikonfigurasi. Set VITE_SUPABASE_URL dan VITE_SUPABASE_PUBLISHABLE_KEY di .env.local' },
      }),
      signUp: async (_params: any) => ({
        data: { session: null, user: null },
        error: { message: 'Supabase belum dikonfigurasi. Set VITE_SUPABASE_URL dan VITE_SUPABASE_PUBLISHABLE_KEY di .env.local' },
      }),
    },
    from: (_table: string) => ({
      select: (_cols?: string) => makeSelectable(),
    }),
    channel: (_name: string) => ({
      on: (_event: any, _filter: any, _cb: any) => ({
        subscribe: () => ({}),
      }),
    }),
    removeChannel: (_channel: any) => {},
  };

  if (typeof window !== 'undefined') {
    console.warn('[Supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Using stub client.');
  }
  return stub;
}

export const supabase = (() => {
  try {
    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      throw new Error('Missing Supabase env vars');
    }
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  } catch (e) {
    return createSupabaseStub();
  }
})();